"""
Application constants.
"""

# Time windows
DAILY_WINDOW_HOUR = 6  # 6AM PT
DAILY_WINDOW_TIMEZONE = "America/Los_Angeles"
HISTORY_DAYS = 90

# Scoring thresholds
MIN_MENTIONS_FOR_ENTITY = 3
MIN_CONFIDENCE_FOR_DISPLAY = 0.3
DORMANT_DAYS = 90
POLARIZATION_THRESHOLD = 0.3

# Recency weighting
RECENCY_HALF_LIFE_HOURS = 8.0

# Implicit mention weighting
IMPLICIT_WEIGHT = 0.5

# Entity types
ENTITY_TYPE_PERSON = "PERSON"
ENTITY_TYPE_SHOW = "SHOW"
ENTITY_TYPE_FILM = "FILM"
ENTITY_TYPE_FRANCHISE = "FRANCHISE"
ENTITY_TYPE_NETWORK_STREAMER = "NETWORK_STREAMER"
ENTITY_TYPE_COUPLE = "COUPLE"
ENTITY_TYPE_BRAND = "BRAND"
ENTITY_TYPE_CHARACTER = "CHARACTER"
